name: idle_tracker
description: A tiny package that tracks idleness in a web application.
version: 0.0.2
homepage: https://github.com/jolleekin/idle_tracker
author: mhoang <jolleekin@outlook.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dev_dependencies:
  build_runner: ^0.10.0
  build_web_compilers: ^0.4.0
